apiVersion: v2
name: saferwall
description: A hackable malware sandbox for the 21st Century
type: application
version: 0.0.3
appVersion: 0.0.3
home: https://saferwall.com
icon: https://saferwall.com/favicon.png
sources:
    - https://github.com/saferwall/saferwall
maintainers:
    - name: Saferwall
      email: admin@saferwall.com
dependencies:
    - name: minio
      version: 5.0.31
      repository: https://kubernetes-charts.storage.googleapis.com/
      condition: minio.enabled
    - name: couchbase-operator
      version: 2.0.2
      repository: https://couchbase-partners.github.io/helm-charts/
      condition: couchbase-operator.enabled
    - name: efs-provisioner
      version: 0.13.1
      repository: https://kubernetes-charts.storage.googleapis.com/
      condition: efs-provisioner.enabled
    - name: nfs-server-provisioner
      version: 1.1.1
      repository: https://kubernetes-charts.storage.googleapis.com/
      condition: nfs-server-provisioner.enabled
    - name: cert-manager
      version: 1.0.3
      repository: https://charts.jetstack.io
      condition: cert-manager.enabled
    - name: ingress-nginx
      version: 3.7.1
      repository: https://kubernetes.github.io/ingress-nginx/
      condition: ingress-nginx.enabled
    - name: filebeat
      version: 7.9.3
      repository: https://helm.elastic.co
      condition: filebeat.enabled
    - name: elasticsearch
      version: 7.9.3
      repository: https://helm.elastic.co
      condition: elasticsearch.enabled
    - name: kibana
      version: 7.9.3
      repository: https://helm.elastic.co
      condition: kibana.enabled
    - name: prometheus-operator
      version: 9.3.2
      repository: https://prometheus-community.github.io/helm-charts
      condition: prometheus-operator.enabled
