{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saferwall.frontend.fullname" . }}
  labels:
    app: {{ include "saferwall.frontend.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "saferwall.frontend.fullname" . }}
  replicas:  {{ .Values.frontend.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "saferwall.frontend.fullname" . }}
    spec:
      {{ if eq .Values.global.privateRegistryServer true }}
      imagePullSecrets:
        - name: regcred
      {{- end }}
      containers:
        - name: "{{ .Values.frontend.name }}"
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          resources:
            requests:
              memory: "{{ .Values.frontend.resources.requests.memory }}"
              cpu: "{{ .Values.frontend.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.frontend.resources.limits.memory }}"
              cpu: "{{ .Values.frontend.resources.limits.cpu }}"
          env:
            - name: VUE_APP_BACKEND_HOST
              value: "{{ .Values.global.backendHostname }}"
{{- end }}
