apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-k8s-wait-for
rules:
- apiGroups: ["core"]
  resources: ["services","pods","jobs"]
  verbs: ["get","watch","list"]
- apiGroups: ["batch"]
  resources: ["services","pods","jobs"]
  verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-k8s-wait-for
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-k8s-wait-for
  apiGroup: rbac.authorization.k8s.io
