{{- if .Values.multiav.enabled }}
{{- $root := . -}}
{{- range $av, $value := .Values.multiav.vendors }}
{{- if $value.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saferwall.multiav.fullname" $root }}-{{ $av }}
  labels:
    app: {{ include "saferwall.multiav.fullname" $root }}-{{ $av }}
spec:
  selector:
    matchLabels:
      app: {{ include "saferwall.multiav.fullname" $root }}-{{ $av }}
  replicas: {{ $value.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "saferwall.multiav.fullname" $root }}-{{ $av }}
    spec:
      {{ if eq $root.Values.global.privateRegistryServer true }}
      imagePullSecrets:
        - name: regcred
      {{- end }}
      containers:
        - name: "{{ $av }}"
          image: "{{ $value.image.repository }}:{{ $value.image.tag }}"
          imagePullPolicy: "{{ $value.image.pullPolicy }}"
          ports:
            - containerPort: {{ $value.containerPort }}
          resources:
            requests:
              cpu: "{{ $root.Values.multiav.resources.requests.cpu }}"
          volumeMounts:
            - name: samples
              mountPath: /samples
      volumes:
      - name: samples
        persistentVolumeClaim:
          claimName: {{ include "saferwall.fullname" $root }}-samples
---
{{- end }}
{{- end }}
{{- end }}
