version: "3.9"

# Use this docker-compose file to setup the test environment before running the
# tests.

services:
  couchbase:
    image: couchbase/server:6.6.1
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    volumes:
      - couchbase_data:/opt/couchbase/var

  nsqlookupd:
    image: nsqio/nsq:v1.2.0
    command: >
      /nsqlookupd
      --log-level error
    hostname: nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161

  nsqd:
    image: nsqio/nsq:v1.2.0
    command: >
      /nsqd
      --lookupd-tcp-address=nsqlookupd:4160
      --log-level error
    hostname: nsqd
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151

  nsqadmin:
    image: nsqio/nsq:v1.2.0
    command: >
      /nsqadmin
      --lookupd-http-address=nsqlookupd:4161
      --log-level error
    hostname: nsqadmin
    depends_on:
      - nsqlookupd
    ports:
      - 4171:4171

  orchestrator:
    image: saferwall/orchestrator:latest
    environment:
    - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/orchestrator-svc, -config, /saferwall/conf/]
    volumes:
      - samples:/samples
      - /samples:/binaries

  aggregator:
    image: saferwall/aggregator:latest
    depends_on:
      - couchbase
    environment:
    - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/aggregator-svc, -config, /saferwall/conf/]
    restart: always

  pe-svc:
    image: saferwall/pe:latest
    environment:
    - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/pe-svc, -config, /saferwall/conf/]
    volumes:
      - samples:/samples

  meta-svc:
    image: saferwall/gometa:latest
    environment:
    - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/meta-svc, -config, /saferwall/conf/]
    volumes:
      - samples:/samples

  avast:
    image: saferwall/goavast:latest
    environment:
    - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/avast-svc, -config, /saferwall/conf/]
    volumes:
      - samples:/samples

  avira:
    image: saferwall/goavira:latest
    environment:
    - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/avira-svc, -config, /saferwall/conf/]
    volumes:
      - samples:/samples

  bitdefender:
    image: saferwall/gobitdefender:latest
    environment:
    - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/bitdefender-svc, -config, /saferwall/conf/]
    volumes:
      - samples:/samples

  clamav:
    image: saferwall/goclamav:latest
    environment:
    - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/clamav-svc, -config, /saferwall/conf/]
    volumes:
      - samples:/samples

  comodo:
    image: saferwall/gocomodo:latest
    environment:
    - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/comodo-svc, -config, /saferwall/conf/]
    volumes:
      - samples:/samples

  fsecure:
    image: saferwall/gofsecure:latest
    environment:
    - SAFERWALL_DEPLOYMENT_KIND=dev
    entrypoint: [/saferwall/fsecure-svc, -config, /saferwall/conf/]
    volumes:
      - samples:/samples

  faker:
    image: golang:1.16-alpine
    command: sh -c "while true; do echo faker; sleep 1000; done"

volumes:
  minio_data:
  couchbase_data:
  samples:
