log_level = "debug"
download_dir = "/samples"

[backend]
address = "http://web:8080"
admin_user = "admin"
admin_pwd = "password"

[ml]
enabled = true
address = "http://ml-pipeline:8001"

[nsq]
lookupds = ["nsqlookupd:4161",]

[minio]
enabled = true
endpoint = "minio:9000"
seckey = "minio123"
accesskey = "minio"
spacename = "samples"
ssl = false

[multiav]
  enabled = true
  [multiav.vendors]
    [multiav.vendors.avast]
    enabled = false
    address = "avast:50051"

    [multiav.vendors.avira]
    enabled = true
    address = "avira:50051"

    [multiav.vendors.bitdefender]
    enabled = false
    address = "bitdefender:50051"

    [multiav.vendors.clamav]
    enabled = true
    address = "clamav:50051"

    [multiav.vendors.comodo]
    enabled = true
    address = "comodo:50051"

    [multiav.vendors.drweb]
    enabled = false
    address = "drweb:50051"

    [multiav.vendors.eset]
    enabled = false
    address = "eset:50051"

    [multiav.vendors.fsecure]
    enabled = false
    address = "fsecure:50051"

    [multiav.vendors.kaspersky]
    enabled = false
    address = "kaspersky:50051"

    [multiav.vendors.symantec]
    enabled = false
    address = "symantec:50051"

    [multiav.vendors.sophos]
    enabled = false
    address = "sophos:50051"

    [multiav.vendors.mcafee]
    enabled = false
    address = "mcafee:50051"

    [multiav.vendors.trendmicro]
    enabled = false
    address = "trendmicro:50051"

    [multiav.vendors.windefender]
    enabled = true
    address = "windefender:50051"

