[backend]
address = "http://web:8080"
admin_user = "admin"
admin_pwd = "password"

[consumer]
# Possible values "panic", "fatal", "error", "warn", "info", "debug", "trace"
log_level = "debug"
download_dir = "/samples"

[ml]
address = "http://ml-pipeline:8001"

[nsq]
lookupds = ["nsqlookupd:4161",]

[minio]
endpoint = "minio:9000"
seckey = "minio123"
accesskey = "minio"
spacename = "samples"
ssl = false

[multiav]
  enabled = false
  [multiav.avast]
  enabled = false
  addr = "avast:50060"

  [multiav.avira]
  enabled = true
  addr = "avira:50051"

  [multiav.bitdefender]
  enabled = false
  addr = "bitdefender:50061"

  [multiav.clamav]
  enabled = true
  addr = "clamav:50052"

  [multiav.comodo]
  enabled = true
  addr = "comodo:50053"

  [multiav.drweb]
  enabled = false
  addr = "drweb:50062"

  [multiav.eset]
  enabled = false
  addr = "eset:50063"

  [multiav.fsecure]
  enabled = false
  addr = "fsecure:50064"

  [multiav.kaspersky]
  enabled = false
  addr = "kaspersky:50065"

  [multiav.symantec]
  enabled = false
  addr = "symantec:50066"

  [multiav.sophos]
  enabled = false
  addr = "sophos:50067"

  [multiav.mcafee]
  enabled = false
  addr = "mcafee:50068"

  [multiav.windefender]
  enabled = true
  addr = "windefender:50054"