log_level = "debug"
download_dir = "/samples"
headless = true

[backend]
address = "http://web:8080"
admin_user = "admin"
admin_pwd = "password"

[ml]
enabled = false
address = "http://ml-pipeline:8001"

[nsq]
lookupds = ["nsqlookupd:4161",]

[minio]
enabled = false
endpoint = "minio:9000"
seckey = "minio123"
accesskey = "minio"
spacename = "samples"
ssl = false

[multiav]
  enabled = false
  [multiav.vendors]
    [multiav.vendors.avast]
    enabled = false
    addr = "avast:50060"

    [multiav.vendors.avira]
    enabled = true
    addr = "avira:50051"

    [multiav.vendors.bitdefender]
    enabled = false
    addr = "bitdefender:50061"

    [multiav.vendors.clamav]
    enabled = true
    addr = "clamav:50052"

    [multiav.vendors.comodo]
    enabled = true
    addr = "comodo:50053"

    [multiav.vendors.drweb]
    enabled = false
    addr = "drweb:50062"

    [multiav.vendors.eset]
    enabled = false
    addr = "eset:50063"

    [multiav.vendors.fsecure]
    enabled = false
    addr = "fsecure:50064"

    [multiav.vendors.kaspersky]
    enabled = false
    addr = "kaspersky:50065"

    [multiav.vendors.symantec]
    enabled = false
    addr = "symantec:50066"

    [multiav.vendors.sophos]
    enabled = false
    addr = "sophos:50067"

    [multiav.vendors.mcafee]
    enabled = false
    addr = "mcafee:50068"

    [multiav.vendors.windefender]
    enabled = true
    addr = "windefender:50054"

