# Log level verbosity.
log_level = "info"
# Shared volume between all microservices.
shared_volume = "/samples"
# The data source name (DSN) for connecting to the broker server (NSQD)
nsqd = "nsqd:4150"
# Topic name used by the orchestrator service to consume messages.
orchestrator_topic = "topic-filescan"
# Topic name used by the ml service to consume messages.
ml_topic = "topic-ml"