# Log level verbosity.
log_level = "debug"

[consumer]
# The data source name (DSN) for connecting to the service discovery server
# (NSQLookupD).
lookupds = ["localhost:4161"]
# Topic name to consume from.
topic = "topic-aggregator"
# Channel name used in conjunction with topic name.
channel = "chan-aggregator"
# The number of concurrent workers to process the jobs.
concurrency = 1

[db]
# DSN for connecting to the database.
server = "couchbase://localhost"
# Username used to access the db.
username = "Administrator"
# Password used to access the db.
password = "password"
# Name of the couchbase bucket.
bucket_name = "sfw"