name: Magic Go Module
on:
  push:
    paths:
      - 'pkg/magic/**'
  pull_request:
    paths:
      - 'pkg/magic/**'
jobs:
  test:
    name: Build & Test
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Build
        run: cd pkg/magic && go build -v ./...

      - name: Test With Coverage
        run: |
          cd pkg/magic
          go test -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Run Vet & Lint
        run: |
          cd pkg/magic
          go vet .
          golint -set_exit_status=1 .
