name: Go Packages

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build/Test Magic Pkg
      run: |
        cd pkg/magic \
        go test -v