name: Go Packages

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build & Test TriD Go Package
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.4
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup config
      run: cp example.env .env
    
    - name: Install dependency
      uses: make die-install

    - name: Test
      run: |
        cd pkg/trid \
        && export LC_ALL=C \
        && go test -v

