name: Go Packages

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build & Test Gib Go Package
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Checkout
      uses: actions/checkout@v2

    - name: Test
      run: |
        cd pkg/gib \
        && go test -v
